[package]
name = "apq-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]


[dependencies]
pinocchio = "0.8.4"


[dev-dependencies]
solana-instruction = "=2.2.1"
solana-message = "=2.2.1"
solana-pubkey = "=2.2.1"
solana-transaction = "=2.2.1"
litesvm = "0.6.1"
